services:
  - type: web
    name: mindfulai
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py # If script | OR gunicorn if Flask/FastAPI
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:YOUR_PASSWORD@db.qjlveevoebvgxfzmsbzj.supabase.co:5432/postgres
        sync: false
      - key: GITHUB_TOKEN
        value: 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 # 🔴 Replace with Render Secrets!
        sync: false
      - key: SUPABASE_URL
        value: https://qjlveevoebvgxfzmsbzj.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbHZlZXZvZWJ2Z3hmem1zYnpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzM4NjYsImV4cCI6MjA2MjM0OTg2Nn0.JU-AU7U7hQQ-ccv2_xkgkcRiARbuor39Dw2ztQbhiC4
      - key: SESSION_SECRET
        generateValue: true
